GET http://localhost:3000/hello
###
POST http://localhost:3000/hello
Content-Type: application/json
###
PUT http://localhost:3000/hello/karl
### 
DELETE http://localhost:3000/hello/karl

### 
GET http://localhost:3000/users
# User 22 ADMIN
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsYXN0bmFtZSI6ImFoYWgiLCJmaXJzdG5hbWUiOiJjb3Vjb3UiLCJyb2xlIjoiQURNSU4iLCJpZCI6MjIsImlhdCI6MTY3MDIyNzM2OX0.QlFqZ9RwG4NdwzTUx6WGXVuMXpLJ4Blyvhbq4K4lKYo
# User USER
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsYXN0bmFtZSI6bnVsbCwiZmlyc3RuYW1lIjpudWxsLCJyb2xlIjoiVVNFUiIsImlkIjozMCwiaWF0IjoxNjcwMjI4MzQwfQ.KuuTgKvdAKtrjJByCC0Xw-rcUnZ8UYsWeSaf4XSoXkc
###
POST http://localhost:3000/users
Content-Type: application/xml

<users>
  <user>
    <email>karl@test.com</email>
    <password>12345</password>
  </user>
  <user email="karl@test.com" password="12345"/>
</users>
###
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "karl6@test.com",
  "password": "test"
}
### 
GET http://localhost:3000/users/1
###
PUT http://localhost:3000/users/22
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsYXN0bmFtZSI6ImFoYWgiLCJmaXJzdG5hbWUiOiJjb3Vjb3UiLCJyb2xlIjoiQURNSU4iLCJpZCI6MjIsImlhdCI6MTY3MDIyNzM2OX0.QlFqZ9RwG4NdwzTUx6WGXVuMXpLJ4Blyvhbq4K4lKYo
    
{
  "role": "ADMIN"
}
### 
DELETE http://localhost:3000/users/1

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "karl6@test.com",
  "password": "test"
}