services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  server:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=mysql://user:password@mysql:3306/app
    command: sh -c "npm install && npm start"

volumes:
  db-data: {}
